Portage/GHCCore.hs: add ghc-9.0.1 library detection
gentoo-haskell/hackport pull request #93
Opened 2021-03-19 16:30 UTC by l29ah

2021-03-19 21:58 UTC, trofi requested changes

2021-03-19 21:58 UTC, trofi commented on Portage/GHCCore.hs
> +--  , p "Cabal" [3,2,0,0]  package is upgradeable
Wrong cabal version in the comment, should be `3.4.0.0`.

2021-03-19 21:58 UTC, trofi commented on Portage/GHCCore.hs
> +  , p "ghc-boot-th" [9,0,1]
`ghc-bignum` should be added here.

2021-03-19 21:58 UTC, trofi commented on Portage/GHCCore.hs
> +--  , p "haskeline" [0,8,0,0]  package is upgradeable
haskeline version is wrong in the comment, should be `0.8.1.0`

2021-03-19 21:58 UTC, trofi commented on Portage/GHCCore.hs
> +--  , p "exceptions [0,10,4] -- used by haskeline, package is upgradeable
Looks like `exceptions` is used by `ghc` library itself. That effectively makes it unupgradeable.

2021-03-19 21:58 UTC, trofi commented on Portage/GHCCore.hs
> +  --  , p "mtl" [2,2,2]  package is upgradeable(?)
`mtl` and `parsec` are used by `exceptions` (used by `ghc` library itself). That effectively makes them unupgradeable.

2021-03-19 21:58 UTC, trofi commented on Portage/GHCCore.hs
> +  -- , p "terminfo" [0,4,1,4]
`terminfo` is used by `ghc`. We'll need to mark it unupgradeable.

2021-03-19 21:58 UTC, trofi commented on Portage/GHCCore.hs
> +  -- , p "text" [1,2,3,2] dependency of Cabal library
`text` is used by `parsec`. We would have to make it unupgradeable. Also, it's version is `1.2.4.1`.

2021-03-19 21:58 UTC, trofi commented on Portage/GHCCore.hs
> +ghc901 :: (DC.CompilerInfo, InstalledPackageIndex)
You'll also need to add `cabalFromGHC` entry for new `Cabal`.

2022-09-03 21:00 UTC, hololeap commented
This is all very outdated at this point. Reopen if you actually need this.

2022-09-03 21:00 UTC, closed without merging